# Generated by Django 5.2.7 on 2026-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrivals',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
