# """
# Django settings for my_ecommerce project.
#
# Generated by 'django-admin startproject' using Django 3.1.2.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/3.1/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/3.1/ref/settings/
# """
# import os
# from dotenv import load_dotenv
# load_dotenv()
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = '0h=)$t!1jpv4s5y&!m!6al!d5c2s8lbtzjal_*su^-q2)%&a)d'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = False
#
# ALLOWED_HOSTS = [
#     "my-ecommers-backend.onrender.com",
#     "localhost",
#     "127.0.0.1",
#     "*"
# ]
#
# CORS_ALLOW_ALL_ORIGINS = True
#
# CSRF_TRUSTED_ORIGINS = [
#     "https://izumart-v3.vercel.app",
#     "http://localhost:3000",
#     "https://my-ecommers-backend.onrender.com"
# ]
#
# # Application definition
#
# SYSTEM_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'django_extensions',
# ]
#
# THIRD_PARTY_APPS = [
#     'product',
#     'cart',
#     'order',
#     'corsheaders',
# ]
#
# INSTALLED_APPS = SYSTEM_APPS + THIRD_PARTY_APPS
#
# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# ROOT_URLCONF = 'my_ecommerce.urls'
#
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.AllowAny',
#     ]
# }
#
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],  # <--- এখানেই template folder
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'my_ecommerce.wsgi.application'
#
#
# # Database
# # https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
# import os
# import dj_database_url
#
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get("DATABASE_URL"),
#         conn_max_age=600
#     )
# }
#
# # Password validation
# # https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/3.1/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True
# # CORS_ALLOW_ALL_ORIGINS = True
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/3.1/howto/static-files/
#
# # STATIC_URL = '/static/'
# STATIC_URL = "/static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"
#
#
#
# SECRET_KEY = os.environ.get("SECRET_KEY")
# DEBUG = os.environ.get("DEBUG", "False") == "True"
# # ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")



# import os
# from pathlib import Path
# from dotenv import load_dotenv
# import dj_database_url
#
# load_dotenv()
#
# BASE_DIR = Path(__file__).resolve().parent.parent
#
#
# # ========================
# # SECURITY
# # ========================
# SECRET_KEY = os.environ.get("SECRET_KEY")
#
# DEBUG = os.environ.get("DEBUG", "False") == "True"
#
# ALLOWED_HOSTS = os.environ.get(
#     "ALLOWED_HOSTS",
#     "127.0.0.1,localhost"
# ).split(",")
#
#
# # ========================
# # APPLICATIONS
# # ========================
# SYSTEM_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]
#
# THIRD_PARTY_APPS = [
#     'rest_framework',
#     'django_extensions',
#     'corsheaders',
#     'cloudinary',
#     'cloudinary_storage',
# ]
#
# LOCAL_APPS = [
#     'product',
#     'cart',
#     'order',
# ]
#
# INSTALLED_APPS = SYSTEM_APPS + THIRD_PARTY_APPS + LOCAL_APPS
#
#
# # ========================
# # MIDDLEWARE
# # ========================
# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]
#
#
# ROOT_URLCONF = 'my_ecommerce.urls'
#
#
# # ========================
# # TEMPLATES
# # ========================
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
#
# WSGI_APPLICATION = 'my_ecommerce.wsgi.application'
#
#
# # ========================
# # DATABASE
# # ========================
# DATABASES = {
#     "default": dj_database_url.config(
#         default=os.environ.get("DATABASE_URL"),
#         conn_max_age=600
#     )
# }
#
#
# # ========================
# # AUTH
# # ========================
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]
#
#
# # ========================
# # INTERNATIONALIZATION
# # ========================
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True
#
#
# # ========================
# # STATIC / MEDIA
# # ========================
# STATIC_URL = "/static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"
#
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
#
#
# # ========================
# # CORS / CSRF
# # ========================
# CORS_ALLOW_ALL_ORIGINS = True
#
# CORS_ALLOWED_ORIGINS = [
#     "https://izumart-v3.vercel.app",
#     "http://localhost:3000",
# ]
#
# CSRF_TRUSTED_ORIGINS = [
#     "https://izumart-v3.vercel.app",
#     "https://my-ecommers-backend.onrender.com",
# ]
#
#
# # ========================
# # REST FRAMEWORK
# # ========================
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.AllowAny',
#     ]
# }
#
# import os
#
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
#     'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
#     'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
# }
#
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'











import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# ========================
# SECURITY
# ========================
SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# ========================
# APPLICATIONS
# ========================
SYSTEM_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "corsheaders",

    # Cloudinary
    "cloudinary",
    "cloudinary_storage",
]

LOCAL_APPS = [
    "product",
    "cart",
    "order",
]

INSTALLED_APPS = SYSTEM_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# ========================
# MIDDLEWARE
# ========================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "my_ecommerce.urls"


# ========================
# TEMPLATES
# ========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "my_ecommerce.wsgi.application"


# ========================
# DATABASE (Render/Postgres safe)
# ========================
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
    )
}


# ========================
# PASSWORD VALIDATION
# ========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ========================
# INTERNATIONALIZATION
# ========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ========================
# STATIC FILES
# ========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# ========================
# MEDIA (IMPORTANT: Cloudinary handles this)
# ========================

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# (local media not used in production, but safe to keep)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ========================
# CLOUDINARY CONFIG
# ========================
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
}


# ========================
# CORS / CSRF
# ========================
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "https://izumart-v3.vercel.app",
    "http://localhost:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "https://izumart-v3.vercel.app",
    "https://my-ecommers-backend.onrender.com",
]


# ========================
# REST FRAMEWORK
# ========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}


# ========================
# SAFETY CHECK (optional but recommended)
# ========================
if not os.getenv("CLOUDINARY_CLOUD_NAME"):
    print("WARNING: Cloudinary not configured!")