# Generated by Django 5.2.7 on 2026-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
