# Generated by Django 5.2.7 on 2026-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_notificationbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationbanner',
            name='target_url',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
