# Generated by Django 5.2.7 on 2026-05-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='COD', max_length=10),
        ),
    ]
