# Generated by Django 5.2.7 on 2026-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE_BKASH', 'bKash'), ('ONLINE_NAGAD', 'Nagad'), ('ONLINE_ROCKET', 'Rocket'), ('ONLINE_UPAY', 'Upay')], default='COD', max_length=20),
        ),
    ]
