# Generated by Django 5.2.7 on 2026-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_charge_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='COD', max_length=30),
        ),
    ]
